### ISSUE TITLE
Camelcase

### ISSUE THREAD

**Issue by imichaelnorris** [samanthasiow/639-final-project#2]
Python code does not follow PEP 8.  Just make the function variables have underscores

**Comment by samanthasiow** [comment]
<img width="435" alt="screen shot 2015-11-15 at 7 19 49 pm" src="https://cloud.githubusercontent.com/assets/5631650/11172086/e62afefa-8bcd-11e5-9c21-7491b79f2914.png">

**Comment by imichaelnorris** [comment]
closed, after fixing Sam's non-compliant camelCase

**Comment by samanthasiow** [comment]
****OUR non-compliant camelCase
